const FETCH_AUTHORS_REQUEST = 'FETCH_AUTHORS_REQUEST';
const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
const FETCH_AUTHORS_FAILURE  = 'FETCH_AUTHORS_FAILURE';


export {
  FETCH_AUTHORS_REQUEST,
  FETCH_AUTHORS_SUCCESS,
  FETCH_AUTHORS_FAILURE,
};
