const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST';
const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
const FETCH_TEAMS_FAILURE  = 'FETCH_TEAMS_FAILURE';


export {
  FETCH_TEAMS_REQUEST,
  FETCH_TEAMS_SUCCESS,
  FETCH_TEAMS_FAILURE,
};
