const TEXT_TYPING = 'TEXT_TYPING';
const SHOW_MODIFIED_TEXT = 'SHOW_MODIFIED_TEXT';
const BUTTON_CLICK = 'BUTTON_CLICK';
const BUTTON_DBCLICK = 'BUTTON_DBCLICK';
const NUMBERS_TYPING  = 'NUMBERS_TYPING';
const SHOW_SUM = 'SHOW_SUM';

export {
  TEXT_TYPING,
  SHOW_MODIFIED_TEXT,
  BUTTON_CLICK,
  BUTTON_DBCLICK,
  NUMBERS_TYPING,
  SHOW_SUM,
};
